# Generated by Django 2.2.7 on 2020-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricea',
            field=models.FloatField(default=0.0),
        ),
    ]
