# Generated by Django 2.2.7 on 2020-02-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_pricea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricea',
        ),
    ]
